LoadModule auth_openidc_module modules/mod_auth_openidc.so

OIDCProviderMetadataURL https://<OIDC_PROVIDER>/.well-known/openid-configuration
OIDCClientID <CLIENT_ID>
OIDCClientSecret <CLIENT_SECRET>
OIDCRedirectURI https://<YOUR_DOMAIN>/oidc_callback
OIDCCryptoPassphrase <RANDOM_SECRET>

<Location />
    AuthType openid-connect
    Require valid-user
</Location>